name: 'CI protocolos'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push image to dockerhub
        id: docker_build
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/brain-agriculture-frontend
          tags: latest
        env:
          PUBLIC_BACK_URL: ${{ secrets.PUBLIC_BACK_URL }}
